### ISSUE TITLE
not currently building on master

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#375]
ReLU6, BlobDataset, FileBlobDataset seem broken or missing

**Comment by tlikhomanenko** [comment]
Hi @lunixbochs,

How are you building? With cmake?

**Comment by tlikhomanenko** [comment]
Could you try again, I think the error was fixed with commit https://github.com/facebookresearch/flashlight/commit/cd5b82f14bf3d81a1a09c136ada873757c4dc158 in flashlight.

**Comment by jacobkahn** [comment]
@lunixbochs — just built successfully. Can you say more about your setup and issue so I can try to repro?

**Comment by lunixbochs** [comment]
Ah, I didn't notice the flashlight changes, I think that will fix this

**Comment by lunixbochs** [comment]
Ok updating flashlight fixed those errors, now I still have

```
[ 36%] Linking CXX executable Train
CMakeFiles/Train.dir/src/data/W2lBlobsDataset.cpp.o: In function `w2l::W2lBlobsDataset::getLoaderData(long) const':
W2lBlobsDataset.cpp:(.text+0x24a8): undefined reference to `std::vector<float, std::allocator<float> > w2l::loadSound<float>(std::istream&)'
collect2: error: ld returned 1 exit status
CMakeFiles/Train.dir/build.make:1103: recipe for target 'Train' failed
```

I fixed this by adding ```template std::vector<float, std::allocator<float> > w2l::loadSound<float>(std::istream&);``` to Sound.cpp, really no clue what caused it though.

**Comment by jacobkahn** [comment]
@lunixbochs — also seeing an issue with gcc 7.4. Working on a fix.

**Comment by lunixbochs** [comment]
I just did a fresh build with gcc 7.4 and libsndfile against master and it's doing this again :/

**Comment by samin9796** [comment]
I am facing the same error. Any update on how to solve this?

**Comment by jacobkahn** [comment]
This has been really tough to repro/debug — I'll track it in #417.
